apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pv-claim
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "grafana-nfs"
  resources:
    requests:
      storage: 10Gi
