apiVersion: v1
kind: PersistentVolume
metadata:
    name: partition-data
    namespace: dev
    labels:
      release: partition-data
spec:
    capacity:
      storage: 60Gi
    accessModes:
      - ReadWriteMany
    persistentVolumeReclaimPolicy: Delete
    nfs:
      path: /data/partition #这个文件夹要提前在nfs下面创建好
      server: 192.168.206.112
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: partition-data-claim
  namespace: dev
spec:
  accessModes:
    - ReadWriteMany
  resources:  
    requests:
      storage: 60Gi
  selector:
    matchLabels:
      release: partition-data