kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rabbitmq-data-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "pointsmart-nfs-storage"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi