apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pv-claim
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "prometheus-nfs"
  resources:
    requests:
      storage: 200Gi
