apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: lcv3-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "mysql-nfs-dev"
  resources:
    requests:
      storage: 20Gi
