apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: kube-system
spec:
  clusterIP: ""
  type: NodePort
  ports:
  - port: 8086
    nodePort: 8086
  selector:
    app: influxdb
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: influxdb
  namespace: kube-system
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: influxdb
    spec: 
      containers:
      - image: influxdb:1.7.8
        name: influxdb
        ports:
        - containerPort: 8086
          name: influxdb
        volumeMounts:
        - name: influxdb-storage
          mountPath: /data/influxdb
      volumes:
      - name: influxdb-storage
        persistentVolumeClaim:
          claimName: influxdb-pv-claim
