apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv-claim
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "influxdb-nfs-client"
  resources:
    requests:
      storage: 20Gi
